### ISSUE TITLE
genel

### ISSUE THREAD

**Issue by VB10** [yusufkecer/delivery_app#12]
https://github.com/yusufkecer/delivery_app/blob/20927f64e24302c3671fc8641fc57c396cb5f8e9/lib/features/task_list_view/widgets/card.dart#L14

- readme muhakkak düzenlemeni tavsiye ederim
- bir çok sayfada function compnent geördüm bunların düzeltimesi gerekir class widgetlera dönmek
- very good anlaysis kullanarak code format
- static kulanımlar value listanble vs view model layerinde kullanımlar buralar daha dikkatli temiz hale getireiblir

**Comment by yusufkecer** [comment]
proje bitmediği için readme update atmadım, bitince atacağım, componentleri düzenlemeye çalıştım, genel bir refactor atıp static kullanımları gözden geçireceğim.
